2023-12-28 06:33:37,624 INFO    MainThread:7428 [wandb_setup.py:_flush():76] Current SDK version is 0.16.1
2023-12-28 06:33:37,624 INFO    MainThread:7428 [wandb_setup.py:_flush():76] Configure stats pid to 7428
2023-12-28 06:33:37,624 INFO    MainThread:7428 [wandb_setup.py:_flush():76] Loading settings from C:\Users\rs1044\.config\wandb\settings
2023-12-28 06:33:37,624 INFO    MainThread:7428 [wandb_setup.py:_flush():76] Loading settings from c:\Users\rs1044\Documents\GitHub\Mixture-of-Experts-based-Federated-Learning-for-Energy-Forecasting\src\time_series\Federatedlearning\TS_FL_PV_Forecasting_Moe\wandb\settings
2023-12-28 06:33:37,624 INFO    MainThread:7428 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'silent': 'true', 'console': 'off'}
2023-12-28 06:33:37,624 INFO    MainThread:7428 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-12-28 06:33:37,624 INFO    MainThread:7428 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-12-28 06:33:37,624 INFO    MainThread:7428 [wandb_init.py:_log_setup():524] Logging user logs to c:\Users\rs1044\Documents\GitHub\Mixture-of-Experts-based-Federated-Learning-for-Energy-Forecasting\src\time_series\Federatedlearning\TS_FL_PV_Forecasting_Moe\wandb\run-20231228_063337-xgmmv37q\logs\debug.log
2023-12-28 06:33:37,624 INFO    MainThread:7428 [wandb_init.py:_log_setup():525] Logging internal logs to c:\Users\rs1044\Documents\GitHub\Mixture-of-Experts-based-Federated-Learning-for-Energy-Forecasting\src\time_series\Federatedlearning\TS_FL_PV_Forecasting_Moe\wandb\run-20231228_063337-xgmmv37q\logs\debug-internal.log
2023-12-28 06:33:37,624 INFO    MainThread:7428 [wandb_init.py:_jupyter_setup():470] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x0000026A49ECFE10>
2023-12-28 06:33:37,624 INFO    MainThread:7428 [wandb_init.py:init():564] calling init triggers
2023-12-28 06:33:37,624 INFO    MainThread:7428 [wandb_init.py:init():571] wandb.init called with sweep_config: {}
config: {'max_epochs': 1, 'batch_size': 16, 'optimizer': 'Adam', 'learning_rate': 0.001, 'architecture': 'global_soft_dense'}
2023-12-28 06:33:37,624 INFO    MainThread:7428 [wandb_init.py:init():614] starting backend
2023-12-28 06:33:37,624 INFO    MainThread:7428 [wandb_init.py:init():618] setting up manager
2023-12-28 06:33:37,624 INFO    MainThread:7428 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2023-12-28 06:33:37,624 INFO    MainThread:7428 [wandb_init.py:init():624] backend started and connected
2023-12-28 06:33:37,624 INFO    MainThread:7428 [wandb_run.py:_label_probe_notebook():1294] probe notebook
2023-12-28 06:33:37,624 INFO    MainThread:7428 [wandb_run.py:_label_probe_notebook():1304] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-12-28 06:33:37,624 INFO    MainThread:7428 [wandb_init.py:init():716] updated telemetry
2023-12-28 06:33:37,672 INFO    MainThread:7428 [wandb_init.py:init():749] communicating run to backend with 90.0 second timeout
2023-12-28 06:33:38,973 INFO    MainThread:7428 [wandb_run.py:_on_init():2254] communicating current version
2023-12-28 06:33:39,278 INFO    MainThread:7428 [wandb_run.py:_on_init():2263] got version response 
2023-12-28 06:33:39,278 INFO    MainThread:7428 [wandb_init.py:init():800] starting run threads in backend
2023-12-28 06:33:39,487 INFO    MainThread:7428 [wandb_run.py:_console_start():2233] atexit reg
2023-12-28 06:33:39,487 INFO    MainThread:7428 [wandb_run.py:_redirect():2088] redirect: off
2023-12-28 06:33:39,487 INFO    MainThread:7428 [wandb_init.py:init():841] run started, returning control to user process
2023-12-28 06:33:41,415 INFO    MainThread:7428 [wandb_run.py:_finish():1962] finishing run ipe/TS_FL_PV_Forecasting_Moe/xgmmv37q
2023-12-28 06:33:41,415 ERROR   MainThread:7428 [jupyter.py:save_history():437] Run pip install nbformat to save notebook history
2023-12-28 06:33:41,415 INFO    MainThread:7428 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2023-12-28 06:33:41,415 INFO    MainThread:7428 [wandb_init.py:_jupyter_teardown():452] cleaning up jupyter logic
2023-12-28 06:33:41,415 INFO    MainThread:7428 [wandb_run.py:_atexit_cleanup():2202] got exitcode: 0
2023-12-28 06:33:41,415 INFO    MainThread:7428 [wandb_run.py:_restore():2185] restore
2023-12-28 06:33:41,415 INFO    MainThread:7428 [wandb_run.py:_restore():2191] restore done
